
package com.wisdom.util.netca;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NetcaCertAA", targetNamespace = "http://appintf.netcacertaa.netca/", wsdlLocation = "http://14.18.158.147:10980/NetcaCertAA/NetcaCertAAWS?wsdl")
public class NetcaCertAA
    extends Service
{

    private final static URL NETCACERTAA_WSDL_LOCATION;
    private final static WebServiceException NETCACERTAA_EXCEPTION;
    private final static QName NETCACERTAA_QNAME = new QName("http://appintf.netcacertaa.netca/", "NetcaCertAA");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://14.18.158.147:10980/NetcaCertAA/NetcaCertAAWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NETCACERTAA_WSDL_LOCATION = url;
        NETCACERTAA_EXCEPTION = e;
    }

    public NetcaCertAA() {
        super(__getWsdlLocation(), NETCACERTAA_QNAME);
    }

    public NetcaCertAA(URL wsdlLocation) {
        super(wsdlLocation, NETCACERTAA_QNAME);
    }

    public NetcaCertAA(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns WebSevIntfImplDelegate
     */
    @WebEndpoint(name = "NetcaCertAAWS")
    public WebSevIntfImplDelegate getNetcaCertAAWS() {
        return super.getPort(new QName("http://appintf.netcacertaa.netca/", "NetcaCertAAWS"), WebSevIntfImplDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebSevIntfImplDelegate
     */
    @WebEndpoint(name = "NetcaCertAAWS")
    public WebSevIntfImplDelegate getNetcaCertAAWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://appintf.netcacertaa.netca/", "NetcaCertAAWS"), WebSevIntfImplDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NETCACERTAA_EXCEPTION!= null) {
            throw NETCACERTAA_EXCEPTION;
        }
        return NETCACERTAA_WSDL_LOCATION;
    }

}
