
package com.wisdom.util.netca;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebSevIntfImplDelegate", targetNamespace = "http://appintf.netcacertaa.netca/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebSevIntfImplDelegate {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VerifyUserCert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "VerifyUserCert", targetNamespace = "http://appintf.netcacertaa.netca/", className = "netca.verifycert.VerifyUserCert")
    @ResponseWrapper(localName = "VerifyUserCertResponse", targetNamespace = "http://appintf.netcacertaa.netca/", className = "netca.verifycert.VerifyUserCertResponse")
    public String verifyUserCert(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    int arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4);

    /**
     *
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChkOneCert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ChkOneCert", targetNamespace = "http://appintf.netcacertaa.netca/", className = "netca.verifycert.ChkOneCert")
    @ResponseWrapper(localName = "ChkOneCertResponse", targetNamespace = "http://appintf.netcacertaa.netca/", className = "netca.verifycert.ChkOneCertResponse")
    public String chkOneCert(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
